# Basic dependabot.yml file with configuration for two package ecosystems
# GitHub documentation @ https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/authn-service" # Location of package manifests
    commit-message:
      prefix: "pip"
    labels:
      - "triage-required"
    schedule:
      interval: "daily" # How often to check for updates (daily, weekly, monthly)
    reviewers:
      - "bartdelange"
